### ISSUE TITLE
papercut: clippy thinks `usdt::Error` is too large

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/usdt#133]
In a fresh project with usdt 0.3, this function:

```rust
fn foo() -> Result<(), usdt::Error> {
    Ok(())
}
```

produces a clippy warning:

```
warning: the `Err`-variant returned from this function is very large
 --> src/main.rs:1:13
  |
1 | fn foo() -> Result<(), usdt::Error> {
  |             ^^^^^^^^^^^^^^^^^^^^^^^ the `Err`-variant is at least 184 bytes
  |
  = help: try reducing the size of `usdt::Error`, for example by boxing large elements or replacing it with `Box<usdt::Error>`
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err
  = note: `#[warn(clippy::result_large_err)]` on by default
```

It appears the threshold for this lint is errors that are > 128 bytes. This is obviously not a big deal, and may be quite painful to fix, but it is an annoyance if one is aiming for clippy-cleanliness.

**Comment by bnaecker** [comment]
Yeah, that's annoying for sure. I'm personally fine with annotation this type to ignore this clippy lint. @ahl any thoughts?

**Comment by bnaecker** [comment]
Oooo man, an up-to-date clippy is less than pleased with this crate in general :)

**Comment by ahl** [comment]
Yes agreed. Let's add the clippy annotation

**Comment by jgallagher** [comment]
I don't think this can be fixed with an annotation in `usdt` itself: the error is on the `Result<_, _>` that contains a `usdt::Error`. E.g., https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3c1fb623334dea298058259445b1b793 still produces the same clippy warning; allowing `clippy::result_large_err` on the non-result error type doesn't appear to do anything (unsurprising, given the name).

**Comment by jgallagher** [comment]
AFAICT the only way to fix it would be to shrink the `usdt::Error` below clippy's 128-byte threshold :-/

**Comment by bnaecker** [comment]
That’s a good point. I guess we could make the error type itself smaller, such as by boxing its own large variants. I expect the Pest error or the one containing Rules to be the worst offenders.

**Comment by alilleybrinker** [comment]
Using the `-Zprint-type-sizes` flag when compiling would help debug which enum variants are especially large, and thereby reduce their size. See: https://nnethercote.github.io/perf-book/type-sizes.html
