### ISSUE TITLE
USDT probe expansions fail `clippy::cast_lossless` checks starting with Rust 1.79

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/usdt#240]
Propolis runs clippy with the `cast_lossless` warning explicitly enabled (it's disabled by default). Rust 1.79 enabled cast lints in macro expansions (see https://github.com/rust-lang/rust-clippy/blob/master/CHANGELOG.md#rust-179). The expansions of probes that take arguments often (always?) contain some `as i64` conversions that cause this (newly-applied) lint to fire. Suppressing them at each probe invocation is a moderate headache (every probe invocation needs to be tagged with `#[allow(clippy::cast_lossless])`). It would be nice if the generated probe code could use `i64::From` so that USDT users can enable this lint without having to allowlist all their probe sites.

(This is low-urgency for Propolis, since we're OK with just disabling the lint globally, but wanted to get something filed in case this comes up for other projects.)

**Comment by bnaecker** [comment]
Thanks for filing this. I'm happy to look into these conversions and see if we can make them safer. I don't think a straight-up `From` will work, because `i64` (or any integer) does not implement `From<*const T>`. But we'll take a look, thanks!

**Comment by bnaecker** [comment]
It looks like `as usize` might be the best bet here. Since `usize` is guaranteed to be the same size as a pointer, it looks like Clippy no longer triggers this lint. In the future, we could rewrite that to use the unstable `ptr::addr()` function if needed.
