### ISSUE TITLE
test and validate compile-time mistakes

### ISSUE THREAD

**Issue by ahl** [oxidecomputer/usdt#4]
We should have a collection of tests that represent developer errors and ensure that the error messages generated are helpful and reflective of our intentions. For example:

- probe with unsupported parameter type (tell the developer what is supported)
- incorrect parameter type for probe input (sensible type error)
- raw parameters or tuple passed to probe rather than function / closure

**Comment by bnaecker** [comment]
The first of these is partially improved by #7

**Comment by bnaecker** [comment]
Closed by #13
