### ISSUE TITLE
Keep an eye on asm_sym stabilization for MacOS consumers

### ISSUE THREAD

**Issue by pfmooney** [oxidecomputer/usdt#54]
Once asm_sym is stabilized, we should be able to switch over to using stable rust for building usdt consumers on all platforms.
At the moment, it looks like there are a few things to keep an eye on:
- rust-lang/rust#93333 
-  rust-lang/rust#94468

**Comment by ahl** [comment]
... and it will be glorious!

**Comment by pfmooney** [comment]
[soon.gif](https://github.com/rust-lang/rust/issues/93333#issuecomment-1252747998)

**Comment by pfmooney** [comment]
It's happening!: rust-lang/rust#103168

**Comment by bnaecker** [comment]
Closed by #71
