### ISSUE TITLE
Add support for pointers to builtin primitives

### ISSUE THREAD

**Issue by jgallagher** [oxidecomputer/usdt#55]
This came up [in omicron](https://github.com/oxidecomputer/omicron/pull/799#discussion_r832590516), where we wanted to add a probe for raw bytes. A workaround is to use integers; e.g.,

```rust
#[usdt::provider(provider = "blahblah")]
mod probes {
    fn raw_bytes(
        _data: u64, // TODO actually a `*const u8`, but that isn't currently allowed by usdt
        _len: u64, // length of data
    ) {}
}
```

which functions correctly from the dtrace side but is a little awkward on the Rust side.

**Comment by bnaecker** [comment]
Closed by #56
