### ISSUE TITLE
Atomic CAS of probe record versions is spicy

### ISSUE THREAD

**Issue by bnaecker** [oxidecomputer/usdt#58]
To prevent loading and processing a probe record multiple times, we do a [compare-and-swap](https://github.com/oxidecomputer/usdt/blob/c32ec7af3394eee0fbc5c539724f8a89e8a6be48/usdt-impl/src/record.rs#L209) to exchange a sentinel version number of 255 with the actual version. This is a bit...spicy...since the data being modified is referred to through a shared reference, a `&[u8]` of the probe record bytes. We should probably handle this a bit differently, using a unique mutable reference to the underlying data.

**Comment by pfmooney** [comment]
If probe registration was synchronized with a module wide mutex, then we could probably do away with the atomics.  In order to preserve the idempotency, we could still change the version fields in the probe section, just through a `ptr` write, rather than a reference.

**Comment by bnaecker** [comment]
@ahl We originally decided on the CAS operations via assembly, but I don't remember much of the detail around that decision. Do you have opinions about either of these approaches, a module-wide mutex or raw pointers? The former is probably easier, meaning we'd only have to replaces the CAS functions with an update of that static variable. The latter means more extensive changes to the `record` module, replacing the current `&[u8]` with something like a `*mut u8` and length, but would avoid locking.

**Comment by pfmooney** [comment]
I think if you're updating the version, regardless of whether its via atomic or not, that the parsing logic needs to use pointers rather than references.  Changing data covered by an immutable reference is UB, unless I'm mistaken.

**Comment by bnaecker** [comment]
Agreed. In the case of the former, I assumed we wouldn't update the version numbers in the records themselves. The indication that the records have already been processed would be in something like an `AtomicBool`.

**Comment by ahl** [comment]
I don't remember this discussion in detail, but I do recall being concerned that there might be multiple, distinct uses of the usdt crate within a single binary. I realize now that this might reflect a confused understanding of how cargo works...

**Comment by bnaecker** [comment]
Closed by #79
